# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.provision :shell, :path => "manifests/setup.sh"
  config.vm.provision :puppet, :options => ["--modulepath", "/home/vagrant/.puppet/modules"] do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "node-xmpp.pp"
  end
end
