language: node_js
node_js:
- '0.10'
env:
- secure: nKJ7N2c+hez7Qs0sNaiqxzEey5CR6QuMNHJ0k9wwm/HLJfeDut8eTe6ZeZtIsDCVed3vCLV/7tlxW8ZQTOf/vX1F8L0hSeADvAnblGi3xG18K7LTjIs5JvAuxSu1ZLRPZ9PkqpSq7Yx1WUdiza8qcYrfsZrhzre+KfzeRzkjFEp7d5DCycr28fFkxA/gXiggaE4K2l6JZrDlK5dxX4TAMIuzr4vVCCUrtzDXXoiXx6kfXF3YcBq5K6QEA08qJMPmhIqHXpBuaiWBangDlWZObnjkdksid5HGHhVkLG4AschRXE4Xh7FCAOTqKNbsPYVJGWBsQNwDXHRHSMc/b9WpUQ==
notifications:
  email:
    recipients:
      - uproxy-eng@googlegroups.com
    on_success: change
    on_failure: always
before_install:
  - "export DISPLAY=:10.0"
  - "Xvfb :10 -screen 0 1280x1024x24 &"
  - npm install -g grunt-cli bower
install:
  - "google-chrome --version"
  - "firefox -v || echo 'No firefox installed.'"
  - "shippable_retry ./setup.sh install"
script:
  - "grunt test"
